export const DEPLOYMENT_CREATE_REQUEST = "DEPLOYMENT_CREATE_REQUEST";
export const DEPLOYMENT_CREATE_SUCCESS = "DEPLOYMENT_CREATE_SUCCESS";
export const DEPLOYMENT_CREATE_FAIL = "DEPLOYMENT_CREATE_FAIL";
export const DEPLOYMENT_CREATE_RESET = "DEPLOYMENT_CREATE_RESET";

export const DEPLOYMENT_LIST_REQUEST = "DEPLOYMENT_LIST_REQUEST";
export const DEPLOYMENT_LIST_SUCCESS = "DEPLOYMENT_LIST_SUCCESS";
export const DEPLOYMENT_LIST_FAIL = "DEPLOYMENT_LIST_FAIL";

export const DEPLOYMENT_DELETE_REQUEST = "DEPLOYMENT_DELETE_REQUEST";
export const DEPLOYMENT_DELETE_SUCCESS = "DEPLOYMENT_DELETE_SUCCESS";
export const DEPLOYMENT_DELETE_FAIL = "DEPLOYMENT_DELETE_FAIL";

export const DEPLOYMENT_SET_COUNTDOWN = "DEPLOYMENT_SET_COUNTDOWN";
export const DEPLOYMENT_REMOVE_COUNTDOWN = "DEPLOYMENT_REMOVE_COUNTDOWN";
